### PR TITLE
add elixir

### PR DESCRIPTION
**Pull request by TORIFUKUKaiou**
Hey!

add [Elixir](https://elixir-lang.org/)!
[We are the Alchemists, my friends](https://www.youtube.com/watch?v=04854XqcfCY)!!!

This repository is Awesome!
Hope this helps.

### CODE REVIEW

**Comment by mattn** [comment]
Thank you. Could you please fix conflcts?

**Comment by TORIFUKUKaiou** [comment]
Yes. I resolved it, force push.

**Comment by mattn** [comment]
Thank you

**Comment by TORIFUKUKaiou** [comment]
Thank you very much.

**Pull request merged**
